### ISSUE TITLE
error on pelias import

### ISSUE THREAD

**Issue by stefanocudini** [pelias/transit#42]
I'm downloaded this project

builded a newimage in local docker repo.

this is my pelias transit config:
```json
"transit": {
      "datapath": "/data/transit",
      "feeds": [
        {
          "layerId": "stops",
          "url": "https://www.trentinotrasporti.it/opendata/google_transit_urbano_tte.zip",
          "filename": "stops.txt",
          "agencyId": "tte",
          "agencyName": "trentino trasporti esercizio",
          "layerName": "stop"
        }
      ]
    }
```
and run command:
```pelias download transit```
and
 ```pelias import transit```
this genr error:
```
pelias import transit
info: [transit] Importing 1 transit feedsArray.
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/ASM.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/GUM.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/MNP.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/PRI.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/USA.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/USA.override.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/VIR.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/NLD.tsv
debug: [wof-admin-lookup] [postalCityMap] loaded /code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/data/NZL.tsv
info: [wof-pip-service:master] starting with layers neighbourhood,borough,locality,localadmin,county,macrocounty,macroregion,region,dependency,country,empire,continent,marinearea,ocean
/code/pelias/transit/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/code/pelias/transit/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/code/pelias/transit/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/code/pelias/transit/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
/code/pelias/transit/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/code/pelias/transit/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/code/pelias/transit/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/code/pelias/transit/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
/code/pelias/transit/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/code/pelias/transit/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/code/pelias/transit/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/code/pelias/transit/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
/code/pelias/transit/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/code/pelias/transit/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/code/pelias/transit/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/code/pelias/transit/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
/code/pelias/transit/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/code/pelias/transit/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/code/pelias/transit/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/code/pelias/transit/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
info: [transit] Creating read stream for: /data/transit/stops.txt
/code/pelias/transit/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/code/pelias/transit/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/code/pelias/transit/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/code/pelias/transit/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
/code/pelias/transit/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/code/pelias/transit/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/code/pelias/transit/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/code/pelias/transit/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
error: [wof-pip-service:master] neighbourhood worker exited unexpectedly with code 1, signal null
error: [wof-pip-service:master] borough worker exited unexpectedly with code 1, signal null
error: [wof-pip-service:master] locality worker exited unexpectedly with code 1, signal null
error: [wof-pip-service:master] localadmin worker exited unexpectedly with code 1, signal null
error: [wof-pip-service:master] county worker exited unexpectedly with code 1, signal null
error: [wof-pip-service:master] macrocounty worker exited unexpectedly with code 1, signal null
error: [wof-pip-service:master] macroregion worker exited unexpectedly with code 1, signal null
info: [transit] Total time taken: 4.546s

/code/pelias/transit/node_modules/pelias-wof-admin-lookup/src/pip/index.js:137
        throw `${layer} worker shutdown unexpectedly`;
        ^
neighbourhood worker shutdown unexpectedly

```

**Comment by stefanocudini** [comment]
as it is organized it is very, very uncomfortable to contribute to this project :(
I think that CI is broken

**Comment by orangejulius** [comment]
Hi @stefanocudini,
Thanks for the report. It looks like this project was missing a `.dockerignore` file, which could cause issues if you are using a different version of Node.js locally than the one used to build the Pelias Docker images (currently Node.js 12). I opened https://github.com/pelias/transit/pull/44 which should help with that, it would be great if you can test it out.

We definitely don't give this repository much attention, but if you find other issues we're always happy to hear about them.

**Comment by stefanocudini** [comment]
tnks solved and tested!
